#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Navegamos al directorio raíz del proyecto
cd "$(dirname "$0")/.."


dotnet build Tienda-UCN-api.csproj --no-restore --verbosity quiet

echo "Runeando el pre push"
